-- zad 1/1
DESCRIBE departments;
-- zad 2/1
SELECT * FROM regions;
-- zad 3/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees;
-- zad 4/1
SELECT FIRST_NAME AS 'Imię', LAST_NAME AS 'Nazwisko' FROM employees;
-- zad 5/1
SELECT * FROM countries;
SELECT DEPARTMENT_NAME FROM departments;
SELECT HIRE_DATE AS 'data zatrudnienia' FROM employees;
SELECT LAST_NAME AS 'Nazwisko pracownika' FROM employees;
-- zad 6/1
SELECT concat(FIRST_NAME, ' ', LAST_NAME) AS 'Imiona i Nazwiska' FROM employees;
-- zad 7/1
SELECT * FROM employees
ORDER BY LAST_NAME ASC;
-- zad 8/1
SELECT * FROM employees
ORDER BY LAST_NAME DESC;
-- zad 9/1
SELECT LAST_NAME, SALARY FROM employees
ORDER BY SALARY DESC;
-- zad 10/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
ORDER BY SALARY ASC, LAST_NAME DESC;
-- zad 11/1
SELECT DISTINCT LAST_NAME FROM employees;
-- zad 12/1
SELECT * FROM employees
WHERE LAST_NAME = 'Chen';
-- zad 13/1
SELECT LAST_NAME FROM employees
WHERE SALARY < 3000;
-- zad 14/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY BETWEEN 3000 AND 8000;
-- zad 15/1
SELECT DISTINCT JOB_ID FROM employees;
-- zad 16/1
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY FROM employees
WHERE NOT SALARY BETWEEN 4000 AND 12000
ORDER BY SALARY;
-- zad 17/1
SELECT * FROM employees
WHERE EMPLOYEE_ID IN (100, 102, 105, 107);
-- zad 18/1
SELECT LAST_NAME, SALARY, SALARY * 1.2 AS 'premia' FROM employees
WHERE LAST_NAME LIKE 'M%';
-- zad 19/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE LAST_NAME LIKE '%i%' AND LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%o%';
-- zad 20/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = 60;
-- zad 21/1
SELECT * FROM employees
WHERE SALARY NOT BETWEEN 3000 AND 20000;
-- zad 22/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE FIRST_NAME LIKE '_e%';
-- zad 23/1
SELECT DISTINCT DEPARTMENT_ID FROM employees;
-- zad 23/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;
-- zad 24/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;
-- zad 25/1
SELECT FIRST_NAME, LAST_NAME, SALARY * 0.20 FROM employees
WHERE DEPARTMENT_ID = 50;
-- zad 26/1
SELECT *  FROM employees
WHERE DEPARTMENT_ID = 60;
-- zad 27/1
SELECT * FROM departments
WHERE LOCATION_ID > 1500;
-- zad 28/1
SELECT * FROM locations
WHERE CITY LIKE 'S%';
-- zad 29/1
SELECT DISTINCT COUNTRY_ID FROM countries;
-- zad 30/1
SELECT COUNTRY_NAME FROM countries
ORDER BY COUNTRY_NAME ASC;
-- zad 31/1
SELECT LAST_NAME, HIRE_DATE, SALARY, SALARY + 2000 AS 'Pensja po podwyżce' FROM employees;
-- zad 1/2
SELECT concat(FIRST_NAME, ' ' , LAST_NAME) AS 'Osoba', SALARY AS 'Pensja' FROM employees;
-- zad 2/2
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = 100;
-- zad 3/2
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE NOT JOB_ID = 'IT_PROG';
-- zad 4/2
SELECT curdate();
-- zad 5/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees;
-- zad 6/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, extract(year from hire_date) AS 'YEAR' FROM employees
WHERE year(hire_date) > 2005
ORDER BY HIRE_DATE;
-- zad 7/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees
WHERE year(hire_date) = 2007
ORDER BY month(hire_date);
-- zad 8/2
SELECT * FROM employees
WHERE SALARY >= 6000 AND SALARY <= 8000;
-- zad 9/2
SELECT DEPARTMENT_NAME FROM departments
WHERE MANAGER_ID IS NULL;
-- zad 10/2
SELECT * FROM employees
ORDER BY SALARY DESC;
-- zad 11/2
SELECT * FROM employees
WHERE DEPARTMENT_ID = 60
ORDER BY SALARY DESC;
-- zad 12/2
SELECT * FROM employees
WHERE DEPARTMENT_ID IN (50, 60, 100);
-- zad 13/2
SELECT * FROM employees
WHERE DEPARTMENT_ID IN (70, 80, 110) AND SALARY NOT BETWEEN 5000 AND 9000
ORDER BY SALARY;
-- zad 14/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY FROM employees
WHERE JOB_ID = 'ST_CLERK' AND year(hire_date) NOT BETWEEN 2004 AND 2005
ORDER BY HIRE_DATE;
-- zad 15/2
SELECT * FROM employees
WHERE MANAGER_ID IS NULL;
-- zad 16/2
SELECT DISTINCT FIRST_NAME FROM employees
ORDER BY FIRST_NAME;
-- zad 17/2
SELECT DEPARTMENT_NAME FROM departments
WHERE DEPARTMENT_NAME NOT LIKE '__o%';
-- zad 18/2
SELECT * FROM employees
WHERE EMAIL LIKE '%G' AND DEPARTMENT_ID IN (90, 110);
-- zad 19/2
SELECT * FROM departments
WHERE LOCATION_ID != 1700;
-- zad 20/2
SELECT DISTINCT FIRST_NAME FROM employees
WHERE FIRST_NAME LIKE 'K%' OR 'A%'
ORDER BY FIRST_NAME;
-- zad 21/2
SELECT FIRST_NAME, LAST_NAME, SALARY + (SALARY * 0.2) AS 'INCREASED SALARY' FROM employees
WHERE DEPARTMENT_ID IN (50, 60, 80);
-- zad 22/2
SELECT * FROM locations
WHERE POSTAL_CODE IS NULL;
-- zad 23/2
SELECT * FROM departments
WHERE LOCATION_ID > 2000;
-- zad 24/2
SELECT * FROM locations
WHERE CITY NOT LIKE 'T%' AND CITY NOT LIKE 'B%';
-- zad 25/2
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY FROM jobs;
-- zad 26/2
SELECT JOB_TITLE, MIN_SALARY + (MIN_SALARY * 0.1) AS 'MIN INCREASED', MAX_SALARY + (MAX_SALARY * 0.1) AS 'MAX INCREASED' FROM jobs
ORDER BY MIN_SALARY;
-- zad 27/2
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, (MAX_SALARY - MIN_SALARY) AS 'Różnica' FROM jobs
ORDER BY (MAX_SALARY - MIN_SALARY);
-- zad 28/2
SELECT DISTINCT LOCATION_ID FROM departments;
-- zad 29/2
SELECT REGION_NAME FROM regions
ORDER BY REGION_NAME;
-- zad 30/2
SELECT MIN_SALARY, MAX_SALARY FROM jobs
WHERE JOB_TITLE LIKE 'Sale%';