-- zad 1/1
DESCRIBE departments;
-- zad 2/1
SELECT * FROM regions;
-- zad 3/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees;
-- zad 4/1
SELECT FIRST_NAME AS 'Imię', LAST_NAME AS 'Nazwisko' FROM employees;
-- zad 5/1
SELECT * FROM countries;
SELECT DEPARTMENT_NAME FROM departments;
SELECT HIRE_DATE AS 'data zatrudnienia' FROM employees;
SELECT LAST_NAME AS 'Nazwisko pracownika' FROM employees;
-- zad 6/1
SELECT concat(FIRST_NAME, ' ', LAST_NAME) AS 'Imiona i Nazwiska' FROM employees;
-- zad 7/1
SELECT * FROM employees
ORDER BY LAST_NAME ASC;
-- zad 8/1
SELECT * FROM employees
ORDER BY LAST_NAME DESC;
-- zad 9/1
SELECT LAST_NAME, SALARY FROM employees
ORDER BY SALARY DESC;
-- zad 10/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
ORDER BY SALARY ASC, LAST_NAME DESC;
-- zad 11/1
SELECT DISTINCT LAST_NAME FROM employees;
-- zad 12/1
SELECT * FROM employees
WHERE LAST_NAME = 'Chen';
-- zad 13/1
SELECT LAST_NAME FROM employees
WHERE SALARY < 3000;
-- zad 14/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY BETWEEN 3000 AND 8000;
-- zad 15/1
SELECT DISTINCT JOB_ID FROM employees;
-- zad 16/1
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY FROM employees
WHERE NOT SALARY BETWEEN 4000 AND 12000
ORDER BY SALARY;
-- zad 17/1
SELECT * FROM employees
WHERE EMPLOYEE_ID IN (100, 102, 105, 107);
-- zad 18/1
SELECT LAST_NAME, SALARY, SALARY * 1.2 AS 'premia' FROM employees
WHERE LAST_NAME LIKE 'M%';
-- zad 19/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE LAST_NAME LIKE '%i%' AND LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%o%';
-- zad 20/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = 60;
-- zad 21/1
SELECT * FROM employees
WHERE SALARY NOT BETWEEN 3000 AND 20000;
-- zad 22/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE FIRST_NAME LIKE '_e%';
-- zad 23/1
SELECT DISTINCT DEPARTMENT_ID FROM employees;
-- zad 23/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;
-- zad 24/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;