-- zad 1/1
DESCRIBE departments;
-- zad 2/1
SELECT * FROM regions;
-- zad 3/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees;
-- zad 4/1
SELECT FIRST_NAME AS 'Imię', LAST_NAME AS 'Nazwisko' FROM employees;
-- zad 5/1
SELECT * FROM countries;
SELECT DEPARTMENT_NAME FROM departments;
SELECT HIRE_DATE AS 'data zatrudnienia' FROM employees;
SELECT LAST_NAME AS 'Nazwisko pracownika' FROM employees;
-- zad 6/1
SELECT concat(FIRST_NAME, ' ', LAST_NAME) AS 'Imiona i Nazwiska' FROM employees;
-- zad 7/1
SELECT * FROM employees
ORDER BY LAST_NAME ASC;
-- zad 8/1
SELECT * FROM employees
ORDER BY LAST_NAME DESC;
-- zad 9/1
SELECT LAST_NAME, SALARY FROM employees
ORDER BY SALARY DESC;
-- zad 10/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
ORDER BY SALARY ASC, LAST_NAME DESC;
-- zad 11/1
SELECT DISTINCT LAST_NAME FROM employees;
-- zad 12/1
SELECT * FROM employees
WHERE LAST_NAME = 'Chen';
-- zad 13/1
SELECT LAST_NAME FROM employees
WHERE SALARY < 3000;
-- zad 14/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY BETWEEN 3000 AND 8000;
-- zad 15/1
SELECT DISTINCT JOB_ID FROM employees;
-- zad 16/1
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY FROM employees
WHERE NOT SALARY BETWEEN 4000 AND 12000
ORDER BY SALARY;
-- zad 17/1
SELECT * FROM employees
WHERE EMPLOYEE_ID IN (100, 102, 105, 107);
-- zad 18/1
SELECT LAST_NAME, SALARY, SALARY * 1.2 AS 'premia' FROM employees
WHERE LAST_NAME LIKE 'M%';
-- zad 19/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE LAST_NAME LIKE '%i%' AND LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%o%';
-- zad 20/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = 60;
-- zad 21/1
SELECT * FROM employees
WHERE SALARY NOT BETWEEN 3000 AND 20000;
-- zad 22/1
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE FIRST_NAME LIKE '_e%';
-- zad 23/1
SELECT DISTINCT DEPARTMENT_ID FROM employees;
-- zad 23/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;
-- zad 24/1
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > 9000;
-- zad 25/1
SELECT FIRST_NAME, LAST_NAME, SALARY * 0.20 FROM employees
WHERE DEPARTMENT_ID = 50;
-- zad 26/1
SELECT *  FROM employees
WHERE DEPARTMENT_ID = 60;
-- zad 27/1
SELECT * FROM departments
WHERE LOCATION_ID > 1500;
-- zad 28/1
SELECT * FROM locations
WHERE CITY LIKE 'S%';
-- zad 29/1
SELECT DISTINCT COUNTRY_ID FROM countries;
-- zad 30/1
SELECT COUNTRY_NAME FROM countries
ORDER BY COUNTRY_NAME ASC;
-- zad 31/1
SELECT LAST_NAME, HIRE_DATE, SALARY, SALARY + 2000 AS 'Pensja po podwyżce' FROM employees;
-- zad 1/2
SELECT concat(FIRST_NAME, ' ' , LAST_NAME) AS 'Osoba', SALARY AS 'Pensja' FROM employees;
-- zad 2/2
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = 100;
-- zad 3/2
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE NOT JOB_ID = 'IT_PROG';
-- zad 4/2
SELECT curdate();
-- zad 5/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees;
-- zad 6/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, extract(year from hire_date) AS 'YEAR' FROM employees
WHERE year(hire_date) > 2005
ORDER BY HIRE_DATE;
-- zad 7/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees
WHERE year(hire_date) = 2007
ORDER BY month(hire_date);
-- zad 8/2
SELECT * FROM employees
WHERE SALARY >= 6000 AND SALARY <= 8000;
-- zad 9/2
SELECT DEPARTMENT_NAME FROM departments
WHERE MANAGER_ID IS NULL;
-- zad 10/2
SELECT * FROM employees
ORDER BY SALARY DESC;
-- zad 11/2
SELECT * FROM employees
WHERE DEPARTMENT_ID = 60
ORDER BY SALARY DESC;
-- zad 12/2
SELECT * FROM employees
WHERE DEPARTMENT_ID IN (50, 60, 100);
-- zad 13/2
SELECT * FROM employees
WHERE DEPARTMENT_ID IN (70, 80, 110) AND SALARY NOT BETWEEN 5000 AND 9000
ORDER BY SALARY;
-- zad 14/2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY FROM employees
WHERE JOB_ID = 'ST_CLERK' AND year(hire_date) NOT BETWEEN 2004 AND 2005
ORDER BY HIRE_DATE;
-- zad 15/2
SELECT * FROM employees
WHERE MANAGER_ID IS NULL;
-- zad 16/2
SELECT DISTINCT FIRST_NAME FROM employees
ORDER BY FIRST_NAME;
-- zad 17/2
SELECT DEPARTMENT_NAME FROM departments
WHERE DEPARTMENT_NAME NOT LIKE '__o%';
-- zad 18/2
SELECT * FROM employees
WHERE EMAIL LIKE '%G' AND DEPARTMENT_ID IN (90, 110);
-- zad 19/2
SELECT * FROM departments
WHERE LOCATION_ID != 1700;
-- zad 20/2
SELECT DISTINCT FIRST_NAME FROM employees
WHERE FIRST_NAME LIKE 'K%' OR 'A%'
ORDER BY FIRST_NAME;
-- zad 21/2
SELECT FIRST_NAME, LAST_NAME, SALARY + (SALARY * 0.2) AS 'INCREASED SALARY' FROM employees
WHERE DEPARTMENT_ID IN (50, 60, 80);
-- zad 22/2
SELECT * FROM locations
WHERE POSTAL_CODE IS NULL;
-- zad 23/2
SELECT * FROM departments
WHERE LOCATION_ID > 2000;
-- zad 24/2
SELECT * FROM locations
WHERE CITY NOT LIKE 'T%' AND CITY NOT LIKE 'B%';
-- zad 25/2
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY FROM jobs;
-- zad 26/2
SELECT JOB_TITLE, MIN_SALARY + (MIN_SALARY * 0.1) AS 'MIN INCREASED', MAX_SALARY + (MAX_SALARY * 0.1) AS 'MAX INCREASED' FROM jobs
ORDER BY MIN_SALARY;
-- zad 27/2
SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, (MAX_SALARY - MIN_SALARY) AS 'Różnica' FROM jobs
ORDER BY (MAX_SALARY - MIN_SALARY);
-- zad 28/2
SELECT DISTINCT LOCATION_ID FROM departments;
-- zad 29/2
SELECT REGION_NAME FROM regions
ORDER BY REGION_NAME;
-- zad 30/2
SELECT MIN_SALARY, MAX_SALARY FROM jobs
WHERE JOB_TITLE LIKE 'Sale%';
-- zad 1/3
SELECT count(*) AS 'Liczba pracowników' FROM employees;
-- zad 2/3
SELECT avg(salary) FROM employees;
-- zad 3/3
SELECT DISTINCT FIRST_NAME FROM employees
WHERE FIRST_NAME LIKE 'A%';
-- zad 4/3
SELECT avg(salary), min(salary), max(salary) FROM employees;
-- zad 5/3
SELECT sum(salary), avg(salary), min(salary), max(salary) FROM employees
WHERE MANAGER_ID IS NOT NULL;
-- zad 6/3
SELECT JOB_ID, sum(salary) FROM employees
GROUP BY JOB_ID;
-- zad 7/3
SELECT JOB_ID, count(*) FROM employees
GROUP BY JOB_ID;
-- zad 8/3
SELECT avg(salary), JOB_ID, count(*) FROM employees
GROUP BY JOB_ID
HAVING count(*) >= 3;
-- zad 9/3
SELECT FIRST_NAME, count(*) FROM employees
GROUP BY FIRST_NAME
HAVING count(first_name) > 1
ORDER BY count(*);
-- zad 10/3
SELECT DEPARTMENT_ID,  avg(SALARY) FROM employees
GROUP BY DEPARTMENT_ID
HAVING avg(SALARY) > 9000;
-- zad 11/3
SELECT DEPARTMENT_ID, max(salary), min(salary), max(salary) - min(salary) AS 'Różnica' FROM employees
GROUP BY DEPARTMENT_ID;
-- zad 12/3
SELECT max(SALARY), MANAGER_ID FROM employees
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
ORDER BY MANAGER_ID;
-- zad 13/3
SELECT max(SALARY), DEPARTMENT_ID FROM employees
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY max(SALARY);
-- zad 14/3
SELECT DEPARTMENT_ID, count(EMPLOYEE_ID), count(SALARY) FROM employees
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING count(SALARY) > 1;
-- zad 15/3
SELECT DISTINCT avg(SALARY), DEPARTMENT_ID FROM employees
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY 1;
-- zad 16/3
SELECT DEPARTMENT_ID, max(SALARY) FROM employees
WHERE DEPARTMENT_ID IN (50, 60, 100)
GROUP BY DEPARTMENT_ID;
-- zad 17/3
SELECT DEPARTMENT_ID, min(SALARY) FROM employees
WHERE LAST_NAME NOT LIKE '%o%'
GROUP BY DEPARTMENT_ID;
-- zad 18/3
SELECT DEPARTMENT_ID, min(SALARY), max(SALARY), count(EMPLOYEE_ID) FROM employees
GROUP BY DEPARTMENT_ID
HAVING count(EMPLOYEE_ID) < 5;
-- zad 19/3
SELECT DEPARTMENT_ID, count(DEPARTMENT_ID) FROM employees
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID;
-- zad 20/3
SELECT DEPARTMENT_ID, min(year(hire_date)), max(year(hire_date)) FROM employees
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;
-- zad 21/3
SELECT JOB_ID, count(*) FROM employees
GROUP BY JOB_ID
ORDER BY count(*) DESC;
-- zad 22/3
SELECT JOB_ID, count(*) FROM employees
GROUP BY JOB_ID
HAVING count(*) > 10;
-- zad 23/3
SELECT JOB_ID, avg(SALARY), count(*), HIRE_DATE FROM employees
GROUP BY JOB_ID
HAVING year(hire_date) != 2005;
-- zad 24/3
SELECT MANAGER_ID, min(SALARY)FROM employees
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;
-- zad 25/3
SELECT avg(SALARY), JOB_ID FROM employees
WHERE JOB_ID IN ('ST_CLERK', 'ST_MAN')
GROUP BY JOB_ID;
-- zad 26/3
SELECT DEPARTMENT_ID, (MAX_SALARY - MIN_SALARY) AS 'Różnica' FROM jobs j
JOIN employees e ON j.JOB_ID = e.JOB_ID
WHERE DEPARTMENT_ID IN (50, 60, 100);
-- zad 27/3
SELECT DEPARTMENT_ID, avg(SALARY), HIRE_DATE FROM employees
WHERE DEPARTMENT_ID IN (70, 80, 110)
GROUP BY DEPARTMENT_ID
HAVING year(hire_date) NOT BETWEEN 2004 AND 2005;
-- zad 28/3
SELECT DISTINCT FIRST_NAME FROM employees
ORDER BY FIRST_NAME;
-- zad 29/3
SELECT CITY, count(DEPARTMENT_ID) FROM departments d
JOIN locations l ON d.LOCATION_ID = l.LOCATION_ID
GROUP BY CITY;
-- zad 30/3
SELECT MANAGER_ID, count(DEPARTMENT_ID), DEPARTMENT_ID FROM departments
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;
-- zad 1/4
SELECT DEPARTMENT_ID, round(avg(salary), 2), truncate(avg(salary), 2), avg(SALARY) FROM employees
GROUP BY DEPARTMENT_ID;
-- zad 2/4
SELECT upper(last_name), char_length(last_name) FROM employees;
-- zad 3/4
SELECT upper(region_name) FROM regions;
-- zad 4/4
SELECT SALARY, round((SALARY * 15.5), 1) FROM employees;
-- zad 5/4
SELECT sqrt(salary), pow(salary, 2) FROM employees;
-- zad 6/4
SELECT LPAD(COUNTRY_NAME, 20, '*') FROM  countries;
-- zad 7/4
SELECT JOB_TITLE, rpad(JOB_TITLE, 4, job_title) FROM jobs;
-- zad 8/4
SELECT JOB_TITLE, lower(rpad(JOB_TITLE, 4, job_title)) FROM jobs;
-- zad 9/4
SELECT replace(FIRST_NAME, 'a', '*') FROM employees;
-- zad 10/4
SELECT LAST_NAME,  substr(upper(last_name), 2) FROM employees
GROUP BY LAST_NAME
HAVING substr(upper(last_name), 2) RLIKE '^[APR]';
-- zad 11/4
SELECT * FROM employees
WHERE LAST_NAME RLIKE '[Kk]';
-- zad 12/4
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME FROM employees e
JOIN departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;
-- zad 13/4
SELECT COUNTRY_NAME, REGION_NAME FROM countries c
JOIN regions r ON c.REGION_ID = r.REGION_ID;
-- zad 14/4
SELECT MAX_SALARY, MIN_SALARY, DEPARTMENT_NAME FROM jobs j
JOIN job_history jh ON j.JOB_ID = jh.JOB_ID
JOIN departments d ON jh.DEPARTMENT_ID = d.DEPARTMENT_ID;
-- zad 15/4
SELECT DEPARTMENT_NAME, count(*) AS 'number of employees' FROM employees e
JOIN departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
ORDER BY count(*);
-- zad 16/4
SELECT DEPARTMENT_NAME, min(SALARY), max(SALARY) FROM departments d
JOIN employees e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
ORDER BY max(SALARY)
